# ai_code_generator/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: codegen-service
spec:
  type: NodePort
  selector:
    app: codegen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
